### ISSUE TITLE
Could not find generator 'tailwindcss:install'

### ISSUE THREAD

**Issue by shenhf** [IcaliaLabs/tailwindcss-rails#4]
```
➜  tailwind git:(master) ✗ rails g tailwindcss:install
Running via Spring preloader in process 22856
Could not find generator 'tailwindcss:install'. Maybe you meant 'css:assets', 'scss:assets' or 'test_unit:system'
Run `rails generate --help` for more options.
```

**Comment by mitchwd** [comment]
Are you sure you ran `bundle install` before running the generator?

**Comment by kurenn** [comment]
@shenhf Did you made it work with @mitchwd suggestion?

**Comment by shenhf** [comment]
Sure,  "bundle install" is ok and "rails g tailwindcss:install" not working.

```
$ rvm current
ruby-2.5.1@rails52
```

**Comment by kurenn** [comment]
Have you tried `bundle exec rails g tailwindcss:install`?

**Comment by fladson** [comment]
I am getting the same error.

```
bundle exec rails g tailwindcss:install                          
Could not find generator 'tailwindcss:install'. Maybe you meant 'responders:install', 'devise:install' or 'rspec:install'
Run `rails generate --help` for more options.
```

```
bundle info tailwindcss                                              
  * tailwindcss (0.1.1)
	Summary: Tailwind CSS Rails Integration + Webpacker
	Homepage: https://github.com/IcaliaLabs/tailwindcss-rails
	Path: /Users/fladson/.rvm/gems/ruby-2.4.1/gems/tailwindcss-0.1.1
```

**Comment by kurenn** [comment]
I kind of figured it out, but not sure how to fix the compilation of the gem, which is the current issue. 

I made it work with:

```ruby
gem "tailwindcss", github: "IcaliaLabs/tailwindcss-rails"
```

Try that, and you should be good to go.

I'll leave this open in order to fix the problem

**Comment by kurenn** [comment]
I just published the solution, and updated the gem at rubygems, version 0.2.0 is the one you can use see - https://github.com/IcaliaLabs/tailwindcss-rails/pull/5 - for more information.

Just run `bundle update tailwindcss` and make sure you have the 0.2.0 version
