### ISSUE TITLE
Ability to Work With Middleman

### ISSUE THREAD

**Issue by delusioninabox** [IcaliaLabs/tailwindcss-rails#7]
I want to use Tailwind CSS with Middleman, but having some issues. Hoping this can be done! 🙏

I copied the tailwind files into my middleman source directory (`/source/javascripts/`) and updated the paths in the webpack and yml files. This seems to work fine for rendering from this directory.

However, I get this error on my localhost with middleman:

```undefined method `javascript_pack_tag' for #<#<Class:0x00007ff8d52ccb00>:0x00007ff8d57e8e68> Did you mean? javascript_include_tag```

Do I need to create new helpers for this?

The CSS doesn't seem to be pulling the compiled version either, though I see they exist in `/public/`. Is there a way to change the export directory into my middleman `/source/` one?

And if this is way more effort than it's worth, just let me know. 😄 I'll figure something out. Thanks!

**Comment by delusioninabox** [comment]
Nevermind, this blog post helped me out. ^^ https://vcavallo.github.io/css/static_site_generator/how_to/2017/12/06/setting-up-middleman-with-tailwind-css.html

**Comment by kurenn** [comment]
Sorry, but yeah this gem's intention is to work only with Rails, and no support for Middleman is planned, but it is good to know you found out! 😄
