### ISSUE TITLE
Install command fails to configure PostCSS correctly

### ISSUE THREAD

**Issue by christophermlne** [IcaliaLabs/tailwindcss-rails#8]
After I first ran the install command, none of the tailwind classes were available until I manually altered `postcss.config.js' as per:  

```
module.exports = {
  plugins: [
    require('tailwindcss'), // added this line
    require('autoprefixer'), // added this line
    require('postcss-import'),
    require('postcss-flexbugs-fixes'),
    require('postcss-preset-env')({
      autoprefixer: {
        flexbox: 'no-2009'
      },
      stage: 3
    })
  ]
}
```

**Comment by kurenn** [comment]
Can you give a little bit more context on the issue? what happened after that?

**Comment by christophermlne** [comment]
After that i was able to use the tailwind classes in my markup.
Let me know what additional context would be useful to you.

**Comment by BobbyMcWho** [comment]
I don't even have that file

**Comment by christophermlne** [comment]
> I don't even have that file

I'm assuming it's generated by Tailwind. Here is some information about it from the Tailwind docs, which is how I figured out how to fix my installation:  
https://tailwindcss.com/docs/installation/#using-tailwind-with-postcss

Also, it looks like there's a major new release of Tailwind, which might be why we're seeing differences between what the generator is producing and what is expected by PostCSS...
Here is the 'upgrading to 1.0' guide: https://tailwindcss.com/docs/upgrading-to-v1

**Comment by BobbyMcWho** [comment]
I've submitted a PR to make this gem support Rails 5.2,  and tailwindcss 1.0 releases. I didn't test on older versions of Rails or tailwinds, since both have breaking configuration changes. 
https://github.com/IcaliaLabs/tailwindcss-rails/pull/9

**Comment by kurenn** [comment]
I'm closing this issue as the PR #9 solves it! Thanks for this @BobbyMcWho 

@christophermlne Have you tried it?
